"use client"
import './globals.css'
import type { Metadata } from 'next'
import { useState } from 'react'
import { DarkTheme, LightTheme } from './theme/theme';
import { ThemeProvider, CssBaseline } from '@mui/material'
import Header from "@/components/Header/Header"



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [isDark, setIsDark] = useState(false);
  
  const switchTheme: any = () => {
    setIsDark(!isDark);
  }

  return (
    <html lang="en">
    <ThemeProvider theme={isDark ? DarkTheme : LightTheme}>
      <CssBaseline/>
      <body>
      <Header switchTheme={switchTheme} isDark={isDark} />
      {children}
      </body>
    </ThemeProvider>
    </html>
  )
}
